services:
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example-password
  #   volumes:
  #     - mongo-data:/data/db
  #   networks:
  #     - my-network
  #   healthcheck:
  #     test: ["CMD", "mongoadmin", "ping", "-h", "localhost"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 3
  # the-gate-keeper:
  #   build:
  #     dockerfile: TheGatekeeper.Server/Dockerfile
  #   ports:
  #     - "8891:80"
  #   networks:
  #     - my-network
  # frontend-runner:
  #   stdin_open: true
  #   image: nginx:latest
  #   build:
  #     context: .
  #     dockerfile: src/Dockerfile
  #   ports:
  #     - 443:80
  #   networks:
  #     - my-network


  the-gate-keeper:
    build:
      dockerfile: TheGatekeeper.Server/Dockerfile
    secrets:
      - api_key
      - mongoDbConnectionString
      - mongoDbUser
      - mongoDbPassword
      - discordWebhook
    ports:
      - "8891:80"
      # - "8891:8890"
      # - "7234:7234"
    networks:
      - my-network

secrets:
  api_key:
    file: ./secrets/api_key
  mongoDbConnectionString:
    file: ./secrets/mongoDbConnectionString
  mongoDbUser:
    file: ./secrets/mongoDbUser
  mongoDbPassword:
    file: ./secrets/mongoDbPassword
  discordWebhook:
    file: ./secrets/discordWebhook

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data: