using MongoDB.Driver;

namespace TheGateKeeper.Server.InfrastructureService
{
    public class ItemSeedService : IHostedService
    {
        private readonly ILogger<ItemSeedService> _logger;
        private readonly IMongoDatabase _database;

        public ItemSeedService(IMongoClient mongoClient, ILogger<ItemSeedService> logger)
        {
            _database = mongoClient.GetDatabase("gateKeeper");
            _logger = logger;
        }

        public async Task StartAsync(CancellationToken cancellationToken)
        {
            _logger.LogInformation("ItemSeedService: Starting item seed...");
            try
            {
                await SeedItems(cancellationToken);
                _logger.LogInformation("ItemSeedService: Item seed completed successfully");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "ItemSeedService: Item seed failed");
            }
        }

        public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;

        private async Task SeedItems(CancellationToken cancellationToken)
        {
            var collection = _database.GetCollection<ItemDaoV1>("items");
            var existingCount = await collection.CountDocumentsAsync(FilterDefinition<ItemDaoV1>.Empty, cancellationToken: cancellationToken);

            if (existingCount > 0)
            {
                _logger.LogInformation("ItemSeedService: Items collection already populated ({Count} items). Skipping seed.", existingCount);
                return;
            }

            var items = GetAllItems();
            if (items.Count == 0)
            {
                _logger.LogWarning("ItemSeedService: No items to seed.");
                return;
            }

            await collection.InsertManyAsync(items, cancellationToken: cancellationToken);
            _logger.LogInformation("ItemSeedService: Seeded {Count} items into the database.", items.Count);
        }

        private static List<ItemDaoV1> GetAllItems()
        {
            return
            [
                new() { ItemId = 1001, Name = "Boots" },
                new() { ItemId = 1004, Name = "Faerie Charm" },
                new() { ItemId = 1006, Name = "Rejuvenation Bead" },
                new() { ItemId = 1011, Name = "Giant's Belt" },
                new() { ItemId = 1018, Name = "Cloak of Agility" },
                new() { ItemId = 1026, Name = "Blasting Wand" },
                new() { ItemId = 1027, Name = "Sapphire Crystal" },
                new() { ItemId = 1028, Name = "Ruby Crystal" },
                new() { ItemId = 1029, Name = "Cloth Armor" },
                new() { ItemId = 1031, Name = "Chain Vest" },
                new() { ItemId = 1033, Name = "Null-Magic Mantle" },
                new() { ItemId = 1035, Name = "Emberknife" },
                new() { ItemId = 1036, Name = "Long Sword" },
                new() { ItemId = 1037, Name = "Pickaxe" },
                new() { ItemId = 1038, Name = "B. F. Sword" },
                new() { ItemId = 1039, Name = "Hailblade" },
                new() { ItemId = 1040, Name = "Obsidian Edge" },
                new() { ItemId = 1042, Name = "Dagger" },
                new() { ItemId = 1043, Name = "Recurve Bow" },
                new() { ItemId = 1052, Name = "Amplifying Tome" },
                new() { ItemId = 1053, Name = "Vampiric Scepter" },
                new() { ItemId = 1054, Name = "Doran's Shield" },
                new() { ItemId = 1055, Name = "Doran's Blade" },
                new() { ItemId = 1056, Name = "Doran's Ring" },
                new() { ItemId = 1057, Name = "Negatron Cloak" },
                new() { ItemId = 1058, Name = "Needlessly Large Rod" },
                new() { ItemId = 1082, Name = "Dark Seal" },
                new() { ItemId = 1083, Name = "Cull" },
                new() { ItemId = 1090, Name = "Quest: Top" },
                new() { ItemId = 1091, Name = "Quest: Mid" },
                new() { ItemId = 1092, Name = "Quest: Bot" },
                new() { ItemId = 1093, Name = "Quest: Support" },
                new() { ItemId = 1094, Name = "Quest: Jungle" },
                new() { ItemId = 1101, Name = "Scorchclaw Pup" },
                new() { ItemId = 1102, Name = "Gustwalker Hatchling" },
                new() { ItemId = 1103, Name = "Mosstomper Seedling" },
                new() { ItemId = 1104, Name = "Eye of the Herald" },
                new() { ItemId = 1105, Name = "Mosstomper Seedling" },
                new() { ItemId = 1106, Name = "Gustwalker Hatchling" },
                new() { ItemId = 1107, Name = "Scorchclaw Pup" },
                new() { ItemId = 1111, Name = "Jarvan I's" },
                new() { ItemId = 1200, Name = "Top Lane Quest" },
                new() { ItemId = 1201, Name = "Mid Lane Quest" },
                new() { ItemId = 1202, Name = "Bot Lane Quest" },
                new() { ItemId = 1203, Name = "Support Quest" },
                new() { ItemId = 1204, Name = "Jungle Quest" },
                new() { ItemId = 1206, Name = "Mid Lane Quest" },
                new() { ItemId = 1207, Name = "Bot Lane Quest" },
                new() { ItemId = 1208, Name = "Support Quest" },
                new() { ItemId = 1209, Name = "Jungle Quest" },
                new() { ItemId = 1220, Name = "Unleashed Teleport" },
                new() { ItemId = 1221, Name = "Top Lane Quest" },
                new() { ItemId = 1222, Name = "Top Lane Quest" },
                new() { ItemId = 123430, Name = "Rite of Ruin" },
                new() { ItemId = 124011, Name = "Sword of Blossoming Dawn" },
                new() { ItemId = 126697, Name = "Hubris" },
                new() { ItemId = 1500, Name = "Penetrating Bullets" },
                new() { ItemId = 1501, Name = "Fortification" },
                new() { ItemId = 1502, Name = "Reinforced Armor" },
                new() { ItemId = 1503, Name = "Warden's Eye" },
                new() { ItemId = 1504, Name = "Vanguard" },
                new() { ItemId = 1505, Name = "Reinforced Armor" },
                new() { ItemId = 1506, Name = "Reinforced Armor" },
                new() { ItemId = 1507, Name = "Overcharged" },
                new() { ItemId = 1508, Name = "Anti-tower Socks" },
                new() { ItemId = 1509, Name = "Gusto" },
                new() { ItemId = 1510, Name = "Phreakish Gusto" },
                new() { ItemId = 1511, Name = "Super Mech Armor" },
                new() { ItemId = 1512, Name = "Super Mech Power Field" },
                new() { ItemId = 1515, Name = "Turret Plating" },
                new() { ItemId = 1516, Name = "Structure Bounty" },
                new() { ItemId = 1517, Name = "Structure Bounty" },
                new() { ItemId = 1518, Name = "Structure Bounty" },
                new() { ItemId = 1519, Name = "Structure Bounty" },
                new() { ItemId = 1520, Name = "OvererchargedHA" },
                new() { ItemId = 1521, Name = "Fortification" },
                new() { ItemId = 1522, Name = "Tower Power-Up" },
                new() { ItemId = 1523, Name = "Overcharged" },
                new() { ItemId = 1524, Name = "Overgrowth" },
                new() { ItemId = 2001, Name = "Recall" },
                new() { ItemId = 2002, Name = "Enhanced Recall" },
                new() { ItemId = 2003, Name = "Health Potion" },
                new() { ItemId = 2007, Name = "Disabled Recall" },
                new() { ItemId = 2010, Name = "Total Biscuit of Everlasting Will" },
                new() { ItemId = 2015, Name = "Kircheis Shard" },
                new() { ItemId = 2019, Name = "Steel Sigil" },
                new() { ItemId = 2020, Name = "The Brutalizer" },
                new() { ItemId = 2021, Name = "Tunneler" },
                new() { ItemId = 2022, Name = "Glowing Mote" },
                new() { ItemId = 2031, Name = "Refillable Potion" },
                new() { ItemId = 2033, Name = "Corrupting Potion" },
                new() { ItemId = 2049, Name = "Guardian's Amulet" },
                new() { ItemId = 2050, Name = "Guardian's Shroud" },
                new() { ItemId = 2051, Name = "Guardian's Horn" },
                new() { ItemId = 2052, Name = "Poro-Snax" },
                new() { ItemId = 2055, Name = "Control Ward" },
                new() { ItemId = 2056, Name = "Stealth Ward" },
                new() { ItemId = 2065, Name = "Shurelya's Battlesong" },
                new() { ItemId = 2138, Name = "Elixir of Iron" },
                new() { ItemId = 2139, Name = "Elixir of Sorcery" },
                new() { ItemId = 2140, Name = "Elixir of Wrath" },
                new() { ItemId = 2141, Name = "Cappa Juice" },
                new() { ItemId = 2142, Name = "Juice of Power" },
                new() { ItemId = 2143, Name = "Juice of Vitality" },
                new() { ItemId = 2144, Name = "Juice of Haste" },
                new() { ItemId = 2145, Name = "Lucky Dice" },
                new() { ItemId = 2146, Name = "Enhanced Lucky Dice" },
                new() { ItemId = 2150, Name = "Elixir of Skill" },
                new() { ItemId = 2151, Name = "Elixir of Avarice" },
                new() { ItemId = 2152, Name = "Elixir of Force" },
                new() { ItemId = 2161, Name = "Bandle Juice of Power" },
                new() { ItemId = 2162, Name = "Bandle Juice of Vitality" },
                new() { ItemId = 2163, Name = "Bandle Juice of Haste" },
                new() { ItemId = 220000, Name = "Stat Bonus" },
                new() { ItemId = 220001, Name = "Legendary Fighter Item" },
                new() { ItemId = 220002, Name = "Legendary Marksman Item" },
                new() { ItemId = 220003, Name = "Legendary Assassin Item" },
                new() { ItemId = 220004, Name = "Legendary Mage Item" },
                new() { ItemId = 220005, Name = "Legendary Tank Item" },
                new() { ItemId = 220006, Name = "Legendary Support Item" },
                new() { ItemId = 220007, Name = "Prismatic Item" },
                new() { ItemId = 220008, Name = "Anvil Voucher" },
                new() { ItemId = 220009, Name = "Gold Stat Anvil Voucher" },
                new() { ItemId = 220010, Name = "Prismatic Stat Voucher" },
                new() { ItemId = 220011, Name = "Bravery Voucher" },
                new() { ItemId = 221011, Name = "Giant's Belt" },
                new() { ItemId = 221026, Name = "Blasting Wand" },
                new() { ItemId = 221031, Name = "Chain Vest" },
                new() { ItemId = 221038, Name = "B. F. Sword" },
                new() { ItemId = 221043, Name = "Recurve Bow" },
                new() { ItemId = 221053, Name = "Vampiric Scepter" },
                new() { ItemId = 221057, Name = "Negatron Cloak" },
                new() { ItemId = 221058, Name = "Needlessly Large Rod" },
                new() { ItemId = 222022, Name = "Glowing Mote" },
                new() { ItemId = 222051, Name = "Guardian's Horn" },
                new() { ItemId = 222065, Name = "Shurelya's Battlesong" },
                new() { ItemId = 222141, Name = "Cappa Juice" },
                new() { ItemId = 222502, Name = "Unending Despair" },
                new() { ItemId = 222503, Name = "Blackfire Torch" },
                new() { ItemId = 222504, Name = "Kaenic Rookern" },
                new() { ItemId = 222510, Name = "Dusk and Dawn" },
                new() { ItemId = 222512, Name = "Fiendhunter Bolts" },
                new() { ItemId = 222517, Name = "Endless Hunger" },
                new() { ItemId = 222522, Name = "Actualizer" },
                new() { ItemId = 222523, Name = "Hexoptics C44" },
                new() { ItemId = 222524, Name = "Bandlepipes" },
                new() { ItemId = 222525, Name = "Protoplasm Harness" },
                new() { ItemId = 222526, Name = "Whispering Circlet" },
                new() { ItemId = 222530, Name = "Diadem of Songs" },
                new() { ItemId = 223001, Name = "Evenshroud" },
                new() { ItemId = 223002, Name = "Trailblazer" },
                new() { ItemId = 223003, Name = "Archangel's Staff" },
                new() { ItemId = 223004, Name = "Manamune" },
                new() { ItemId = 223005, Name = "Ghostcrawlers" },
                new() { ItemId = 223006, Name = "Berserker's Greaves" },
                new() { ItemId = 223009, Name = "Boots of Swiftness" },
                new() { ItemId = 223011, Name = "Chemtech Putrifier" },
                new() { ItemId = 223020, Name = "Sorcerer's Shoes" },
                new() { ItemId = 223026, Name = "Guardian Angel" },
                new() { ItemId = 223031, Name = "Infinity Edge" },
                new() { ItemId = 223032, Name = "Yun Tal Wildarrows" },
                new() { ItemId = 223033, Name = "Mortal Reminder" },
                new() { ItemId = 223036, Name = "Lord Dominik's Regards" },
                new() { ItemId = 223039, Name = "Atma's Reckoning" },
                new() { ItemId = 223040, Name = "Seraph's Embrace" },
                new() { ItemId = 223042, Name = "Muramana" },
                new() { ItemId = 223046, Name = "Phantom Dancer" },
                new() { ItemId = 223047, Name = "Plated Steelcaps" },
                new() { ItemId = 223050, Name = "Zeke's Convergence" },
                new() { ItemId = 223053, Name = "Sterak's Gage" },
                new() { ItemId = 223057, Name = "Sheen" },
                new() { ItemId = 223065, Name = "Spirit Visage" },
                new() { ItemId = 223067, Name = "Kindlegem" },
                new() { ItemId = 223068, Name = "Sunfire Aegis" },
                new() { ItemId = 223071, Name = "Black Cleaver" },
                new() { ItemId = 223072, Name = "Bloodthirster" },
                new() { ItemId = 223073, Name = "Experimental Hexplate" },
                new() { ItemId = 223074, Name = "Ravenous Hydra" },
                new() { ItemId = 223075, Name = "Thornmail" },
                new() { ItemId = 223078, Name = "Trinity Force" },
                new() { ItemId = 223084, Name = "Heartsteel" },
                new() { ItemId = 223085, Name = "Runaan's Hurricane" },
                new() { ItemId = 223087, Name = "Statikk Shiv" },
                new() { ItemId = 223089, Name = "Rabadon's Deathcap" },
                new() { ItemId = 223091, Name = "Wit's End" },
                new() { ItemId = 223094, Name = "Rapid Firecannon" },
                new() { ItemId = 223095, Name = "Stormrazor" },
                new() { ItemId = 223100, Name = "Lich Bane" },
                new() { ItemId = 223102, Name = "Banshee's Veil" },
                new() { ItemId = 223105, Name = "Aegis of the Legion" },
                new() { ItemId = 223107, Name = "Redemption" },
                new() { ItemId = 223109, Name = "Knight's Vow" },
                new() { ItemId = 223110, Name = "Frozen Heart" },
                new() { ItemId = 223111, Name = "Mercury's Treads" },
                new() { ItemId = 223112, Name = "Guardian's Orb" },
                new() { ItemId = 223115, Name = "Nashor's Tooth" },
                new() { ItemId = 223116, Name = "Rylai's Crystal Scepter" },
                new() { ItemId = 223118, Name = "Malignance" },
                new() { ItemId = 223119, Name = "Winter's Approach" },
                new() { ItemId = 223121, Name = "Fimbulwinter" },
                new() { ItemId = 223124, Name = "Guinsoo's Rageblade" },
                new() { ItemId = 223135, Name = "Void Staff" },
                new() { ItemId = 223137, Name = "Cryptbloom" },
                new() { ItemId = 223139, Name = "Mercurial Scimitar" },
                new() { ItemId = 223142, Name = "Youmuu's Ghostblade" },
                new() { ItemId = 223143, Name = "Randuin's Omen" },
                new() { ItemId = 223146, Name = "Hextech Gunblade" },
                new() { ItemId = 223152, Name = "Hextech Rocketbelt" },
                new() { ItemId = 223153, Name = "Blade of The Ruined King" },
                new() { ItemId = 223156, Name = "Maw of Malmortius" },
                new() { ItemId = 223157, Name = "Zhonya's Hourglass" },
                new() { ItemId = 223158, Name = "Ionian Boots of Lucidity" },
                new() { ItemId = 223161, Name = "Spear of Shojin" },
                new() { ItemId = 223165, Name = "Morellonomicon" },
                new() { ItemId = 223172, Name = "Zephyr" },
                new() { ItemId = 223177, Name = "Guardian's Blade" },
                new() { ItemId = 223181, Name = "Hullbreaker" },
                new() { ItemId = 223184, Name = "Guardian's Hammer" },
                new() { ItemId = 223185, Name = "Guardian's Dirk" },
                new() { ItemId = 223190, Name = "Locket of the Iron Solari" },
                new() { ItemId = 223193, Name = "Gargoyle Stoneplate" },
                new() { ItemId = 223222, Name = "Mikael's Blessing" },
                new() { ItemId = 223302, Name = "Terminus" },
                new() { ItemId = 223504, Name = "Ardent Censer" },
                new() { ItemId = 223508, Name = "Essence Reaver" },
                new() { ItemId = 223742, Name = "Dead Man's Plate" },
                new() { ItemId = 223748, Name = "Titanic Hydra" },
                new() { ItemId = 223814, Name = "Edge of Night" },
                new() { ItemId = 224004, Name = "Spectral Cutlass" },
                new() { ItemId = 224005, Name = "Imperial Mandate" },
                new() { ItemId = 224401, Name = "Force of Nature" },
                new() { ItemId = 224403, Name = "The Golden Spatula" },
                new() { ItemId = 224628, Name = "Horizon Focus" },
                new() { ItemId = 224629, Name = "Cosmic Drive" },
                new() { ItemId = 224633, Name = "Riftmaker" },
                new() { ItemId = 224636, Name = "Night Harvester" },
                new() { ItemId = 224637, Name = "Demonic Embrace" },
                new() { ItemId = 224644, Name = "Crown of the Shattered Queen" },
                new() { ItemId = 224645, Name = "Shadowflame" },
                new() { ItemId = 224646, Name = "Stormsurge" },
                new() { ItemId = 226035, Name = "Silvermere Dawn" },
                new() { ItemId = 226333, Name = "Death's Dance" },
                new() { ItemId = 226609, Name = "Chempunk Chainsword" },
                new() { ItemId = 226610, Name = "Sundered Sky" },
                new() { ItemId = 226616, Name = "Staff of Flowing Water" },
                new() { ItemId = 226617, Name = "Moonstone Renewer" },
                new() { ItemId = 226620, Name = "Echoes of Helia" },
                new() { ItemId = 226621, Name = "Dawncore" },
                new() { ItemId = 226630, Name = "Goredrinker" },
                new() { ItemId = 226631, Name = "Stridebreaker" },
                new() { ItemId = 226632, Name = "Divine Sunderer" },
                new() { ItemId = 226653, Name = "Liandry's Anguish" },
                new() { ItemId = 226655, Name = "Luden's Echo" },
                new() { ItemId = 226656, Name = "Everfrost" },
                new() { ItemId = 226657, Name = "Rod of Ages" },
                new() { ItemId = 226662, Name = "Iceborn Gauntlet" },
                new() { ItemId = 226664, Name = "Hollow Radiance" },
                new() { ItemId = 226665, Name = "Jak'Sho, The Protean" },
                new() { ItemId = 226667, Name = "Radiant Virtue" },
                new() { ItemId = 226671, Name = "Galeforce" },
                new() { ItemId = 226672, Name = "Kraken Slayer" },
                new() { ItemId = 226673, Name = "Immortal Shieldbow" },
                new() { ItemId = 226675, Name = "Navori Flickerblades" },
                new() { ItemId = 226676, Name = "The Collector" },
                new() { ItemId = 226691, Name = "Duskblade of Draktharr" },
                new() { ItemId = 226692, Name = "Eclipse" },
                new() { ItemId = 226693, Name = "Prowler's Claw" },
                new() { ItemId = 226694, Name = "Serylda's Grudge" },
                new() { ItemId = 226695, Name = "Serpent's Fang" },
                new() { ItemId = 226696, Name = "Axiom Arc" },
                new() { ItemId = 226697, Name = "Hubris" },
                new() { ItemId = 226698, Name = "Profane Hydra" },
                new() { ItemId = 226699, Name = "Voltaic Cyclosword" },
                new() { ItemId = 226701, Name = "Opportunity" },
                new() { ItemId = 228001, Name = "Anathema's Chains" },
                new() { ItemId = 228002, Name = "Wooglet's Witchcap" },
                new() { ItemId = 228003, Name = "Deathblade" },
                new() { ItemId = 228004, Name = "Adaptive Helm" },
                new() { ItemId = 228005, Name = "Obsidian Cleaver" },
                new() { ItemId = 228006, Name = "Sanguine Blade" },
                new() { ItemId = 228008, Name = "Runeglaive" },
                new() { ItemId = 228009, Name = "Multitool" },
                new() { ItemId = 228020, Name = "Abyssal Mask" },
                new() { ItemId = 2403, Name = "Minion Dematerializer" },
                new() { ItemId = 2420, Name = "Seeker's Armguard" },
                new() { ItemId = 2421, Name = "Shattered Armguard" },
                new() { ItemId = 2422, Name = "Slightly Magical Footwear" },
                new() { ItemId = 2501, Name = "Overlord's Bloodmail" },
                new() { ItemId = 2502, Name = "Unending Despair" },
                new() { ItemId = 2503, Name = "Blackfire Torch" },
                new() { ItemId = 2504, Name = "Kaenic Rookern" },
                new() { ItemId = 2508, Name = "Fated Ashes" },
                new() { ItemId = 2510, Name = "Dusk and Dawn" },
                new() { ItemId = 2512, Name = "Fiendhunter Bolts" },
                new() { ItemId = 2517, Name = "Endless Hunger" },
                new() { ItemId = 2520, Name = "Bastionbreaker" },
                new() { ItemId = 2522, Name = "Actualizer" },
                new() { ItemId = 2523, Name = "Hexoptics C44" },
                new() { ItemId = 2524, Name = "Bandlepipes" },
                new() { ItemId = 2525, Name = "Protoplasm Harness" },
                new() { ItemId = 2526, Name = "Whispering Circlet" },
                new() { ItemId = 2530, Name = "Diadem of Songs" },
                new() { ItemId = 3001, Name = "Evenshroud" },
                new() { ItemId = 3002, Name = "Trailblazer" },
                new() { ItemId = 3003, Name = "Archangel's Staff" },
                new() { ItemId = 3004, Name = "Manamune" },
                new() { ItemId = 3005, Name = "Ghostcrawlers" },
                new() { ItemId = 3006, Name = "Berserker's Greaves" },
                new() { ItemId = 3009, Name = "Boots of Swiftness" },
                new() { ItemId = 3010, Name = "Symbiotic Soles" },
                new() { ItemId = 3011, Name = "Chemtech Putrifier" },
                new() { ItemId = 3012, Name = "Chalice of Blessing" },
                new() { ItemId = 3013, Name = "Synchronized Souls" },
                new() { ItemId = 3020, Name = "Sorcerer's Shoes" },
                new() { ItemId = 3023, Name = "Lifewell Pendant" },
                new() { ItemId = 3024, Name = "Glacial Buckler" },
                new() { ItemId = 3026, Name = "Guardian Angel" },
                new() { ItemId = 3031, Name = "Infinity Edge" },
                new() { ItemId = 3032, Name = "Yun Tal Wildarrows" },
                new() { ItemId = 3033, Name = "Mortal Reminder" },
                new() { ItemId = 3035, Name = "Last Whisper" },
                new() { ItemId = 3036, Name = "Lord Dominik's Regards" },
                new() { ItemId = 3039, Name = "Atma's Reckoning" },
                new() { ItemId = 3040, Name = "Seraph's Embrace" },
                new() { ItemId = 3041, Name = "Mejai's Soulstealer" },
                new() { ItemId = 3042, Name = "Muramana" },
                new() { ItemId = 3044, Name = "Phage" },
                new() { ItemId = 3046, Name = "Phantom Dancer" },
                new() { ItemId = 3047, Name = "Plated Steelcaps" },
                new() { ItemId = 3050, Name = "Zeke's Convergence" },
                new() { ItemId = 3051, Name = "Hearthbound Axe" },
                new() { ItemId = 3053, Name = "Sterak's Gage" },
                new() { ItemId = 3057, Name = "Sheen" },
                new() { ItemId = 3065, Name = "Spirit Visage" },
                new() { ItemId = 3066, Name = "Winged Moonplate" },
                new() { ItemId = 3067, Name = "Kindlegem" },
                new() { ItemId = 3068, Name = "Sunfire Aegis" },
                new() { ItemId = 3070, Name = "Tear of the Goddess" },
                new() { ItemId = 3071, Name = "Black Cleaver" },
                new() { ItemId = 3072, Name = "Bloodthirster" },
                new() { ItemId = 3073, Name = "Experimental Hexplate" },
                new() { ItemId = 3074, Name = "Ravenous Hydra" },
                new() { ItemId = 3075, Name = "Thornmail" },
                new() { ItemId = 3076, Name = "Bramble Vest" },
                new() { ItemId = 3077, Name = "Tiamat" },
                new() { ItemId = 3078, Name = "Trinity Force" },
                new() { ItemId = 3082, Name = "Warden's Mail" },
                new() { ItemId = 3083, Name = "Warmog's Armor" },
                new() { ItemId = 3084, Name = "Heartsteel" },
                new() { ItemId = 3085, Name = "Runaan's Hurricane" },
                new() { ItemId = 3086, Name = "Zeal" },
                new() { ItemId = 3087, Name = "Statikk Shiv" },
                new() { ItemId = 3089, Name = "Rabadon's Deathcap" },
                new() { ItemId = 3091, Name = "Wit's End" },
                new() { ItemId = 3094, Name = "Rapid Firecannon" },
                new() { ItemId = 3095, Name = "Stormrazor" },
                new() { ItemId = 3097, Name = "Stormrazor" },
                new() { ItemId = 3100, Name = "Lich Bane" },
                new() { ItemId = 3102, Name = "Banshee's Veil" },
                new() { ItemId = 3105, Name = "Aegis of the Legion" },
                new() { ItemId = 3107, Name = "Redemption" },
                new() { ItemId = 3108, Name = "Fiendish Codex" },
                new() { ItemId = 3109, Name = "Knight's Vow" },
                new() { ItemId = 3110, Name = "Frozen Heart" },
                new() { ItemId = 3111, Name = "Mercury's Treads" },
                new() { ItemId = 3112, Name = "Guardian's Orb" },
                new() { ItemId = 3113, Name = "Aether Wisp" },
                new() { ItemId = 3114, Name = "Forbidden Idol" },
                new() { ItemId = 3115, Name = "Nashor's Tooth" },
                new() { ItemId = 3116, Name = "Rylai's Crystal Scepter" },
                new() { ItemId = 3117, Name = "Mobility Boots" },
                new() { ItemId = 3118, Name = "Malignance" },
                new() { ItemId = 3119, Name = "Winter's Approach" },
                new() { ItemId = 3121, Name = "Fimbulwinter" },
                new() { ItemId = 3123, Name = "Executioner's Calling" },
                new() { ItemId = 3124, Name = "Guinsoo's Rageblade" },
                new() { ItemId = 3128, Name = "Deathfire Grasp" },
                new() { ItemId = 3131, Name = "Sword of the Divine" },
                new() { ItemId = 3133, Name = "Caulfield's Warhammer" },
                new() { ItemId = 3134, Name = "Serrated Dirk" },
                new() { ItemId = 3135, Name = "Void Staff" },
                new() { ItemId = 3137, Name = "Cryptbloom" },
                new() { ItemId = 3139, Name = "Mercurial Scimitar" },
                new() { ItemId = 3140, Name = "Quicksilver Sash" },
                new() { ItemId = 3142, Name = "Youmuu's Ghostblade" },
                new() { ItemId = 3143, Name = "Randuin's Omen" },
                new() { ItemId = 3144, Name = "Scout's Slingshot" },
                new() { ItemId = 3145, Name = "Hextech Alternator" },
                new() { ItemId = 3146, Name = "Hextech Gunblade" },
                new() { ItemId = 3147, Name = "Haunting Guise" },
                new() { ItemId = 3152, Name = "Hextech Rocketbelt" },
                new() { ItemId = 3153, Name = "Blade of The Ruined King" },
                new() { ItemId = 3155, Name = "Hexdrinker" },
                new() { ItemId = 3156, Name = "Maw of Malmortius" },
                new() { ItemId = 3157, Name = "Zhonya's Hourglass" },
                new() { ItemId = 3158, Name = "Ionian Boots of Lucidity" },
                new() { ItemId = 3161, Name = "Spear of Shojin" },
                new() { ItemId = 3165, Name = "Morellonomicon" },
                new() { ItemId = 3170, Name = "Swiftmarch" },
                new() { ItemId = 3171, Name = "Crimson Lucidity" },
                new() { ItemId = 3172, Name = "Gunmetal Greaves" },
                new() { ItemId = 3173, Name = "Chainlaced Crushers" },
                new() { ItemId = 3174, Name = "Armored Advance" },
                new() { ItemId = 3175, Name = "Spellslinger's Shoes" },
                new() { ItemId = 3176, Name = "Forever Forward" },
                new() { ItemId = 3177, Name = "Guardian's Blade" },
                new() { ItemId = 3179, Name = "Umbral Glaive" },
                new() { ItemId = 3181, Name = "Hullbreaker" },
                new() { ItemId = 3184, Name = "Guardian's Hammer" },
                new() { ItemId = 3190, Name = "Locket of the Iron Solari" },
                new() { ItemId = 3193, Name = "Gargoyle Stoneplate" },
                new() { ItemId = 3211, Name = "Spectre's Cowl" },
                new() { ItemId = 322065, Name = "Shurelya's Battlesong" },
                new() { ItemId = 3222, Name = "Mikael's Blessing" },
                new() { ItemId = 322526, Name = "Whispering Circlet" },
                new() { ItemId = 322530, Name = "Diadem of Songs" },
                new() { ItemId = 323002, Name = "Trailblazer" },
                new() { ItemId = 323003, Name = "Archangel's Staff" },
                new() { ItemId = 323004, Name = "Manamune" },
                new() { ItemId = 323040, Name = "Seraph's Embrace" },
                new() { ItemId = 323042, Name = "Muramana" },
                new() { ItemId = 323050, Name = "Zeke's Convergence" },
                new() { ItemId = 323070, Name = "Tear of the Goddess" },
                new() { ItemId = 323075, Name = "Thornmail" },
                new() { ItemId = 323107, Name = "Redemption" },
                new() { ItemId = 323109, Name = "Knight's Vow" },
                new() { ItemId = 323110, Name = "Frozen Heart" },
                new() { ItemId = 323119, Name = "Winter's Approach" },
                new() { ItemId = 323121, Name = "Fimbulwinter" },
                new() { ItemId = 323190, Name = "Locket of the Iron Solari" },
                new() { ItemId = 323222, Name = "Mikael's Blessing" },
                new() { ItemId = 323504, Name = "Ardent Censer" },
                new() { ItemId = 324005, Name = "Imperial Mandate" },
                new() { ItemId = 326616, Name = "Staff of Flowing Water" },
                new() { ItemId = 326617, Name = "Moonstone Renewer" },
                new() { ItemId = 326620, Name = "Echoes of Helia" },
                new() { ItemId = 326621, Name = "Dawncore" },
                new() { ItemId = 326657, Name = "Rod of Ages" },
                new() { ItemId = 328020, Name = "Abyssal Mask" },
                new() { ItemId = 3302, Name = "Terminus" },
                new() { ItemId = 3330, Name = "Scarecrow Effigy" },
                new() { ItemId = 3340, Name = "Stealth Ward" },
                new() { ItemId = 3348, Name = "Arcane Sweeper" },
                new() { ItemId = 3349, Name = "Lucent Singularity" },
                new() { ItemId = 3363, Name = "Farsight Alteration" },
                new() { ItemId = 3364, Name = "Oracle Lens" },
                new() { ItemId = 3398, Name = "Small Party Favor" },
                new() { ItemId = 3399, Name = "Party Favor" },
                new() { ItemId = 3400, Name = "Your Cut" },
                new() { ItemId = 3430, Name = "Rite Of Ruin" },
                new() { ItemId = 3504, Name = "Ardent Censer" },
                new() { ItemId = 3508, Name = "Essence Reaver" },
                new() { ItemId = 3513, Name = "Eye of the Herald" },
                new() { ItemId = 3599, Name = "Kalista's Black Spear" },
                new() { ItemId = 3600, Name = "Kalista's Black Spear" },
                new() { ItemId = 3742, Name = "Dead Man's Plate" },
                new() { ItemId = 3748, Name = "Titanic Hydra" },
                new() { ItemId = 3801, Name = "Crystalline Bracer" },
                new() { ItemId = 3802, Name = "Lost Chapter" },
                new() { ItemId = 3803, Name = "Catalyst of Aeons" },
                new() { ItemId = 3814, Name = "Edge of Night" },
                new() { ItemId = 3850, Name = "Spellthief's Edge" },
                new() { ItemId = 3851, Name = "Frostfang" },
                new() { ItemId = 3853, Name = "Shard of True Ice" },
                new() { ItemId = 3854, Name = "Steel Shoulderguards" },
                new() { ItemId = 3855, Name = "Runesteel Spaulders" },
                new() { ItemId = 3857, Name = "Pauldrons of Whiterock" },
                new() { ItemId = 3858, Name = "Relic Shield" },
                new() { ItemId = 3859, Name = "Targon's Buckler" },
                new() { ItemId = 3860, Name = "Bulwark of the Mountain" },
                new() { ItemId = 3862, Name = "Spectral Sickle" },
                new() { ItemId = 3863, Name = "Harrowing Crescent" },
                new() { ItemId = 3864, Name = "Black Mist Scythe" },
                new() { ItemId = 3865, Name = "World Atlas" },
                new() { ItemId = 3866, Name = "Runic Compass" },
                new() { ItemId = 3867, Name = "Bounty of Worlds" },
                new() { ItemId = 3869, Name = "Celestial Opposition" },
                new() { ItemId = 3870, Name = "Dream Maker" },
                new() { ItemId = 3871, Name = "Zaz'Zak's Realmspike" },
                new() { ItemId = 3876, Name = "Solstice Sleigh" },
                new() { ItemId = 3877, Name = "Bloodsong" },
                new() { ItemId = 3901, Name = "Fire at Will" },
                new() { ItemId = 3902, Name = "Death's Daughter" },
                new() { ItemId = 3903, Name = "Raise Morale" },
                new() { ItemId = 3916, Name = "Oblivion Orb" },
                new() { ItemId = 4003, Name = "Lifeline" },
                new() { ItemId = 4004, Name = "Spectral Cutlass" },
                new() { ItemId = 4005, Name = "Imperial Mandate" },
                new() { ItemId = 4010, Name = "Bloodletter's Curse" },
                new() { ItemId = 4011, Name = "Sword of Blossoming Dawn" },
                new() { ItemId = 4012, Name = "Sin Eater" },
                new() { ItemId = 4013, Name = "Lightning Braid" },
                new() { ItemId = 4014, Name = "Frozen Mallet" },
                new() { ItemId = 4015, Name = "Perplexity" },
                new() { ItemId = 4016, Name = "Wordless Promise" },
                new() { ItemId = 4017, Name = "Hellfire Hatchet" },
                new() { ItemId = 4401, Name = "Force of Nature" },
                new() { ItemId = 4402, Name = "Innervating Locket" },
                new() { ItemId = 4403, Name = "The Golden Spatula" },
                new() { ItemId = 443054, Name = "Darksteel Talons" },
                new() { ItemId = 443055, Name = "Fulmination" },
                new() { ItemId = 443056, Name = "Demon King's Crown" },
                new() { ItemId = 443058, Name = "Shield of Molten Stone" },
                new() { ItemId = 443059, Name = "Cloak of Starry Night" },
                new() { ItemId = 443060, Name = "Sword of the Divine" },
                new() { ItemId = 443061, Name = "Force Of Entropy" },
                new() { ItemId = 443062, Name = "Sanguine Gift" },
                new() { ItemId = 443063, Name = "Eleisa's Miracle" },
                new() { ItemId = 443064, Name = "Talisman Of Ascension" },
                new() { ItemId = 443069, Name = "Hamstringer" },
                new() { ItemId = 443079, Name = "Turbo Chemtank" },
                new() { ItemId = 443080, Name = "Twin Mask" },
                new() { ItemId = 443081, Name = "Hexbolt Companion" },
                new() { ItemId = 443083, Name = "Warmog's Armor" },
                new() { ItemId = 443090, Name = "Reaper's Toll" },
                new() { ItemId = 443193, Name = "Gargoyle Stoneplate" },
                new() { ItemId = 444636, Name = "Night Harvester" },
                new() { ItemId = 444637, Name = "Demonic Embrace" },
                new() { ItemId = 444644, Name = "Crown of the Shattered Queen" },
                new() { ItemId = 446632, Name = "Divine Sunderer" },
                new() { ItemId = 446656, Name = "Everfrost" },
                new() { ItemId = 446667, Name = "Radiant Virtue" },
                new() { ItemId = 446671, Name = "Galeforce" },
                new() { ItemId = 446691, Name = "Duskblade of Draktharr" },
                new() { ItemId = 446693, Name = "Prowler's Claw" },
                new() { ItemId = 447100, Name = "Mirage Blade" },
                new() { ItemId = 447101, Name = "Gambler's Blade" },
                new() { ItemId = 447102, Name = "Reality Fracture" },
                new() { ItemId = 447103, Name = "Hemomancer's Helm" },
                new() { ItemId = 447104, Name = "Innervating Locket" },
                new() { ItemId = 447105, Name = "Empyrean Promise" },
                new() { ItemId = 447106, Name = "Dragonheart" },
                new() { ItemId = 447107, Name = "Decapitator" },
                new() { ItemId = 447108, Name = "Runecarver" },
                new() { ItemId = 447109, Name = "Cruelty" },
                new() { ItemId = 447110, Name = "Moonflair Spellblade" },
                new() { ItemId = 447111, Name = "Overlord's Bloodmail" },
                new() { ItemId = 447112, Name = "Flesheater" },
                new() { ItemId = 447113, Name = "Detonation Orb" },
                new() { ItemId = 447114, Name = "Reverberation" },
                new() { ItemId = 447115, Name = "Regicide" },
                new() { ItemId = 447116, Name = "Kinkou Jitte" },
                new() { ItemId = 447118, Name = "Pyromancer's Cloak" },
                new() { ItemId = 447119, Name = "Lightning Rod" },
                new() { ItemId = 447120, Name = "Diamond-Tipped Spear" },
                new() { ItemId = 447121, Name = "Twilight's Edge" },
                new() { ItemId = 447122, Name = "Black Hole Gauntlet" },
                new() { ItemId = 447123, Name = "Puppeteer" },
                new() { ItemId = 4628, Name = "Horizon Focus" },
                new() { ItemId = 4629, Name = "Cosmic Drive" },
                new() { ItemId = 4630, Name = "Blighting Jewel" },
                new() { ItemId = 4632, Name = "Verdant Barrier" },
                new() { ItemId = 4633, Name = "Riftmaker" },
                new() { ItemId = 4635, Name = "Leeching Leer" },
                new() { ItemId = 4636, Name = "Night Harvester" },
                new() { ItemId = 4637, Name = "Demonic Embrace" },
                new() { ItemId = 4638, Name = "Watchful Wardstone" },
                new() { ItemId = 4641, Name = "Stirring Wardstone" },
                new() { ItemId = 4642, Name = "Bandleglass Mirror" },
                new() { ItemId = 4643, Name = "Vigilant Wardstone" },
                new() { ItemId = 4644, Name = "Crown of the Shattered Queen" },
                new() { ItemId = 4645, Name = "Shadowflame" },
                new() { ItemId = 4646, Name = "Stormsurge" },
                new() { ItemId = 6029, Name = "Ironspike Whip" },
                new() { ItemId = 6032, Name = "Stat Bonus" },
                new() { ItemId = 6035, Name = "Silvermere Dawn" },
                new() { ItemId = 6333, Name = "Death's Dance" },
                new() { ItemId = 6609, Name = "Chempunk Chainsword" },
                new() { ItemId = 6610, Name = "Sundered Sky" },
                new() { ItemId = 6616, Name = "Staff of Flowing Water" },
                new() { ItemId = 6617, Name = "Moonstone Renewer" },
                new() { ItemId = 6620, Name = "Echoes of Helia" },
                new() { ItemId = 6621, Name = "Dawncore" },
                new() { ItemId = 6630, Name = "Goredrinker" },
                new() { ItemId = 663039, Name = "Atma's Reckoning" },
                new() { ItemId = 663056, Name = "Demon King's Crown" },
                new() { ItemId = 663058, Name = "Shield of Molten Stone" },
                new() { ItemId = 663059, Name = "Cloak of Starry Night" },
                new() { ItemId = 663060, Name = "Sword of the Divine" },
                new() { ItemId = 663064, Name = "Veigar's Talisman of Ascension" },
                new() { ItemId = 6631, Name = "Stridebreaker" },
                new() { ItemId = 663146, Name = "Hextech Gunblade" },
                new() { ItemId = 663172, Name = "Zephyr" },
                new() { ItemId = 663193, Name = "Gargoyle Stoneplate" },
                new() { ItemId = 6632, Name = "Divine Sunderer" },
                new() { ItemId = 664011, Name = "Sword of Blossoming Dawn" },
                new() { ItemId = 664403, Name = "The Golden Spatula" },
                new() { ItemId = 664644, Name = "Crown of the Shattered Queen" },
                new() { ItemId = 6653, Name = "Liandry's Torment" },
                new() { ItemId = 6655, Name = "Luden's Echo" },
                new() { ItemId = 6656, Name = "Everfrost" },
                new() { ItemId = 6657, Name = "Rod of Ages" },
                new() { ItemId = 6660, Name = "Bami's Cinder" },
                new() { ItemId = 6662, Name = "Iceborn Gauntlet" },
                new() { ItemId = 6664, Name = "Hollow Radiance" },
                new() { ItemId = 6665, Name = "Jak'Sho, The Protean" },
                new() { ItemId = 6667, Name = "Radiant Virtue" },
                new() { ItemId = 6670, Name = "Noonquiver" },
                new() { ItemId = 6671, Name = "Galeforce" },
                new() { ItemId = 667101, Name = "Gambler's Blade" },
                new() { ItemId = 667109, Name = "Cruelty" },
                new() { ItemId = 667112, Name = "Flesheater" },
                new() { ItemId = 6672, Name = "Kraken Slayer" },
                new() { ItemId = 6673, Name = "Immortal Shieldbow" },
                new() { ItemId = 6675, Name = "Navori Flickerblade" },
                new() { ItemId = 6676, Name = "The Collector" },
                new() { ItemId = 667666, Name = "The Collector" },
                new() { ItemId = 6677, Name = "Rageknife" },
                new() { ItemId = 6690, Name = "Rectrix" },
                new() { ItemId = 6691, Name = "Duskblade of Draktharr" },
                new() { ItemId = 6692, Name = "Eclipse" },
                new() { ItemId = 6693, Name = "Prowler's Claw" },
                new() { ItemId = 6694, Name = "Serylda's Grudge" },
                new() { ItemId = 6695, Name = "Serpent's Fang" },
                new() { ItemId = 6696, Name = "Axiom Arc" },
                new() { ItemId = 6697, Name = "Hubris" },
                new() { ItemId = 6698, Name = "Profane Hydra" },
                new() { ItemId = 6699, Name = "Voltaic Cyclosword" },
                new() { ItemId = 6700, Name = "Shield of the Rakkor" },
                new() { ItemId = 6701, Name = "Opportunity" },
                new() { ItemId = 6702, Name = "Scouting Ahead" },
                new() { ItemId = 7050, Name = "Gangplank Placeholder" },
                new() { ItemId = 8001, Name = "Anathema's Chains" },
                new() { ItemId = 8010, Name = "Bloodletter's Curse" },
                new() { ItemId = 8020, Name = "Abyssal Mask" },
                new() { ItemId = 9168, Name = "Locked Weapon Slot" },
                new() { ItemId = 9171, Name = "Cyclonic Slicers" },
                new() { ItemId = 9172, Name = "YuumiBot" },
                new() { ItemId = 9173, Name = "Radiant Field" },
                new() { ItemId = 9174, Name = "Statikk Sword" },
                new() { ItemId = 9175, Name = "Lioness's Lament" },
                new() { ItemId = 9176, Name = "Gatling Bunny-Guns" },
                new() { ItemId = 9177, Name = "Searing Shortbow" },
                new() { ItemId = 9178, Name = "The Annihilator" },
                new() { ItemId = 9179, Name = "Battle Bunny Crossbow" },
                new() { ItemId = 9180, Name = "UwU Blaster" },
                new() { ItemId = 9181, Name = "Vortex Glove" },
                new() { ItemId = 9183, Name = "Blade-o-rang" },
                new() { ItemId = 9184, Name = "Bunny Mega-Blast" },
                new() { ItemId = 9185, Name = "Anti-Shark Sea Mine" },
                new() { ItemId = 9187, Name = "T.I.B.B.E.R.S" },
                new() { ItemId = 9188, Name = "Ani-Mines" },
                new() { ItemId = 9189, Name = "Final City Transit" },
                new() { ItemId = 9190, Name = "Echoing Batblades" },
                new() { ItemId = 9192, Name = "Paw Print Poisoner" },
                new() { ItemId = 9193, Name = "Iceblast Armor" },
                new() { ItemId = 9271, Name = "Unceasing Cyclone" },
                new() { ItemId = 9272, Name = "YuumiBot_Final_FINAL" },
                new() { ItemId = 9273, Name = "Explosive Embrace" },
                new() { ItemId = 9274, Name = "Prumbis's Electrocarver" },
                new() { ItemId = 9275, Name = "Enveloping Light" },
                new() { ItemId = 9276, Name = "Double Bun-Bun Barrage" },
                new() { ItemId = 9277, Name = "Evolved Embershot" },
                new() { ItemId = 9278, Name = "Animapocalypse" },
                new() { ItemId = 9279, Name = "Bunny Prime Ballista" },
                new() { ItemId = 9280, Name = "OwO Blaster" },
                new() { ItemId = 9281, Name = "Tempest's Gauntlet" },
                new() { ItemId = 9283, Name = "Quad-o-rang" },
                new() { ItemId = 9284, Name = "Rapid Rabbit Raindown" },
                new() { ItemId = 9285, Name = "Neverending Mobstomper" },
                new() { ItemId = 9287, Name = "T.I.B.B.E.R.S (B.E.E.G Edition)" },
                new() { ItemId = 9288, Name = "Jinx's Tri-Namite" },
                new() { ItemId = 9289, Name = "FC Limited Express" },
                new() { ItemId = 9290, Name = "Vayne's Chromablades" },
                new() { ItemId = 9292, Name = "Bearfoot Chem-Dispenser" },
                new() { ItemId = 9293, Name = "Deep Freeze" },
                new() { ItemId = 9300, Name = "Meow Meow" },
                new() { ItemId = 9301, Name = "Shield Slam" },
                new() { ItemId = 9302, Name = "Sound Wave" },
                new() { ItemId = 9303, Name = "Pillory Swipe" },
                new() { ItemId = 9304, Name = "Steel Tempest" },
                new() { ItemId = 9305, Name = "Tentacle Slam" },
                new() { ItemId = 9306, Name = "Winged Dagger" },
                new() { ItemId = 9307, Name = "Guiding Hex" },
                new() { ItemId = 9308, Name = "Bunny Hop" },
                new() { ItemId = 9400, Name = "Battle Cat Barrage" },
                new() { ItemId = 9401, Name = "Light of the Lion" },
                new() { ItemId = 9402, Name = "Anima Echo" },
                new() { ItemId = 9403, Name = "Savage Slice" },
                new() { ItemId = 9404, Name = "Wandering Storms" },
                new() { ItemId = 9405, Name = "Grizzly Smash" },
                new() { ItemId = 9406, Name = "Lover's Ricochet" },
                new() { ItemId = 9407, Name = "Hopped-Up Hex" },
                new() { ItemId = 9408, Name = "Carrot Crash" },
                new() { ItemId = 994403, Name = "Golden Spatula" },
            ];
        }
    }
}
